services:
  - type: web
    name: padlhub-trial-api-ivan
    runtime: docker
    plan: free
    region: frankfurt
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_HOST
        fromService:
          type: web
          name: padlhub-trial-ivan
          envVarKey: RENDER_EXTERNAL_HOSTNAME

  - type: web
    name: padlhub-trial-ivan
    runtime: static
    buildCommand: npm ci && VITE_API_URL=https://${API_HOST}/api npm run build
    staticPublishPath: ./dist
    envVars:
      - key: API_HOST
        fromService:
          type: web
          name: padlhub-trial-api-ivan
          envVarKey: RENDER_EXTERNAL_HOSTNAME
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
