import type { Training } from './schemas/training.schema';

export const trainingSeed: Training[] = [
  {
    id: 1,
    date: '2026-07-14',
    time: '19:00',
    title: 'Первая пробная тренировка',
    station: 'Нагатинская',
    type: 'Американо',
    address: '1-й Нагатинский проезд, 2с17',
    coach: 'Алексей Морозов',
    duration: 60,
    spotsLeft: 2,
    spotsTotal: 4,
    court: 'Корт 3',
  },
  {
    id: 2,
    date: '2026-07-15',
    time: '10:30',
    title: 'Первая пробная тренировка',
    station: 'Терехово',
    type: 'Мексикано',
    address: 'Нижние Мнёвники, 110',
    coach: 'Мария Лебедева',
    duration: 60,
    spotsLeft: 1,
    spotsTotal: 4,
    court: 'Корт 1',
  },
  {
    id: 3,
    date: '2026-07-16',
    time: '18:00',
    title: 'Первая пробная тренировка',
    station: 'Ясенево',
    type: 'Американо',
    address: 'Новоясеневский проспект, 3А',
    coach: 'Полина Конева',
    duration: 90,
    spotsLeft: 3,
    spotsTotal: 4,
    court: 'Корт 2',
  },
  {
    id: 4,
    date: '2026-07-18',
    time: '12:00',
    title: 'Первая пробная тренировка',
    station: 'Нагатинская',
    type: 'Мексикано',
    address: '1-й Нагатинский проезд, 2с17',
    coach: 'Дмитрий Григорьев',
    duration: 60,
    spotsLeft: 4,
    spotsTotal: 4,
    court: 'Корт 5',
  },
  {
    id: 5,
    date: '2026-07-19',
    time: '17:30',
    title: 'Первая пробная тренировка',
    station: 'Терехово',
    type: 'Американо',
    address: 'Нижние Мнёвники, 110',
    coach: 'Ксения Данько',
    duration: 60,
    spotsLeft: 2,
    spotsTotal: 4,
    court: 'Корт 4',
  },
];
